# Generated by Django 5.2.13 on 2026-04-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('systolic_bp', models.IntegerField()),
                ('diastolic_bp', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('blood_glucose', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('activity_level', models.IntegerField(help_text='Scale 1–10')),
                ('diet_quality_score', models.IntegerField(help_text='Scale 1–10')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.patientprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
