# Generated by Django 5.2.4 on 2026-04-28 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('priority', models.IntegerField(help_text='1 = high, 2 = medium, 3 = low')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.patientprofile')),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
