# Generated by Django 5.2.4 on 2026-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='type',
            field=models.CharField(choices=[('trend', 'Trend'), ('condition', 'Condition')], default='condition', max_length=20),
        ),
    ]
