# Generated by Django 5.2.4 on 2026-04-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_insight_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-score', 'priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
