# Generated by Django 5.2.4 on 2026-04-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patientprofile_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='ai_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
