# Generated by Django 5.2.4 on 2026-04-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ai_summary_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='activity_level',
            field=models.IntegerField(blank=True, help_text='Scale 1–10', null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='blood_glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='diastolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='diet_quality_score',
            field=models.IntegerField(blank=True, help_text='Scale 1–10', null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='sleep_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthmetric',
            name='systolic_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
