# Generated by Django 5.2.4 on 2026-04-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_partial_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='activity_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes of physical activity', null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='steps',
            field=models.IntegerField(blank=True, help_text='Step count', null=True),
        ),
    ]
