# Generated by Django 5.2.4 on 2026-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_activity_minutes_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscore',
            name='confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
